feature: ['feature/*', 'feat/*']
refactor: ['refactor/*']
fix: ['fix/*', 'bugfix/*', 'hotfix/*']
style: ['style/*']
chore: ['chore/*']
dependencies: ['deps/*', 'renovate/*']
ci: ['ci/*']
documentation: ['docs/*']
tests: ['tests/*']
optimization: ['optimization/*']