feature: ['feat/*']
refactor: ['refactor/*']
fix: ['fix/*']
style: ['style/*']
chore: ['chore/*']
dependencies: ['deps/*', 'renovate/*']
ci: ['ci/*']
documentation: ['docs/*']
tests: ['test/*']
optimization: ['perf/*']
revert: ['revert/*']